name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-on-comment:
    name: Test on PR Comment
    runs-on: ubuntu-20.04
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/test') &&
      github.event.comment.author_association != 'NONE'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head

    - name: Setup CUDA
      uses: Jimver/cuda-toolkit@v0.2.11
      with:
        cuda: '11.8.0'
        method: 'network'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          libgtest-dev \
          build-essential

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CUDA_ARCHITECTURES=75 \
          -DUSE_TESTS=ON \
          -G Ninja
        ninja

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --build-config Release

    - name: Comment results
      uses: actions/github-script@v7
      with:
        script: |
          const comment = `## 🔄 Tests Triggered by Comment

Tests have been triggered by @${{ github.event.comment.user.login }}'s comment.

### Results
✅ All tests passed successfully!

### Configuration
- **Build Type**: Release
- **CUDA Version**: 11.8
- **Architecture**: 75

### Next Steps
- Review the test results
- If tests pass, consider merging the PR
- If tests fail, check the failure details

---

*This comment was automatically generated by the CI system.*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });