name: Code Quality & Compilation Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ main, develop ]

env:
  BUILD_TYPE: Release

jobs:
  validate-code:
    name: Validate Code Structure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install basic build tools
      run: |
        echo "🔍 Performing static code analysis and basic compilation checks"
        echo "Note: No GPU testing available on GitHub Actions"
        echo ""

        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          gcc \
          g++ \
          build-essential \
          pkg-config

    - name: Check code formatting and structure
      run: |
        echo "=== Code Quality Analysis ==="

        # Check for basic syntax issues
        echo "Checking C++ files for syntax..."
        syntax_errors=0
        find src/ include/ tests/ -name "*.cpp" -o -name "*.cu" -o -name "*.cuh" -o -name "*.h" | \
        while read file; do
          if [ -f "$file" ]; then
            echo "  Checking $file..."
            # Basic syntax check
            if ! head -100 "$file" > /tmp/syntax_check.cpp 2>/dev/null; then
              echo "  ⚠️ Cannot read file: $file"
              continue
            fi
            if ! gcc -fsyntax-only -x c++ /tmp/syntax_check.cpp 2>/dev/null; then
              echo "  ❌ Syntax error in $file"
              syntax_errors=$((syntax_errors + 1))
            fi
          fi
        done

        echo "Syntax check complete. Found $syntax_errors potential issues."

    - name: Check for common issues
      run: |
        echo "=== Code Quality Checks ==="

        # Check for TODO/FIXME comments in production code
        todo_count=$(grep -r "TODO\|FIXME\|XXX" src/ include/ --include="*.cpp" --include="*.cu" --include="*.h" | grep -v "test_" | wc -l)
        if [ "$todo_count" -gt 0 ]; then
          echo "⚠️ Found $todo_count TODO/FIXME comments in production code:"
          grep -r "TODO\|FIXME\|XXX" src/ include/ --include="*.cpp" --include="*.cu" --include="*.h" | grep -v "test_" | head -10
        else
          echo "✅ No TODO/FIXME comments found in production code"
        fi

        # Check for long lines (>120 characters)
        long_lines=$(find src/ include/ tests/ -name "*.cpp" -o -name "*.cu" -o -name "*.cuh" -o -name "*.h" | \
                     xargs awk 'length($0) > 120 { print FILENAME ":" NR ":" $0 }' | wc -l)
        if [ "$long_lines" -gt 0 ]; then
          echo "⚠️ Found $long_lines lines longer than 120 characters"
          find src/ include/ tests/ -name "*.cpp" -o -name "*.cu" -o -name "*.cuh" -o -name "*.h" | \
            xargs awk 'length($0) > 120 { print FILENAME ":" NR ":" $0 }' | head -5
        else
          echo "✅ No lines exceed 120 characters"
        fi

        # Check CMakeLists.txt syntax
        if [ -f "CMakeLists.txt" ]; then
          echo "✅ CMakeLists.txt found"
        else
          echo "❌ CMakeLists.txt not found"
          exit 1
        fi

    - name: Validate project structure
      run: |
        echo "=== Project Structure Validation ==="

        # Check for required directories
        required_dirs=("src" "include" "tests")
        for dir in "${required_dirs[@]}"; do
          if [ -d "$dir" ]; then
            echo "✅ $dir/ directory exists"
          else
            echo "❌ $dir/ directory missing"
          fi
        done

        # Check for key header files
        key_headers=("include/gsdr/gsdr.h" "include/gsdr/qpsk.h" "include/gsdr/qpsk256.h")
        for header in "${key_headers[@]}"; do
          if [ -f "$header" ]; then
            echo "✅ $header exists"
          else
            echo "⚠️ $header not found"
          fi
        done

        # Check for test files
        test_files=$(find tests/ -name "test_*.cpp" 2>/dev/null | wc -l)
        if [ "$test_files" -gt 0 ]; then
          echo "✅ Found $test_files test files"
        else
          echo "⚠️ No test files found"
        fi

    - name: Generate validation report
      if: always()
      run: |
        echo "## 🔍 GSDR Code Quality & Structure Report" > validation_report.md
        echo "" >> validation_report.md
        echo "| Check | Status | Details |" >> validation_report.md
        echo "|-------|--------|---------|" >> validation_report.md

        # Syntax check status
        syntax_errors=$(find src/ include/ tests/ -name "*.cpp" -o -name "*.cu" -o -name "*.cuh" -o -name "*.h" | \
                       xargs -I {} sh -c 'head -100 "{}" > /tmp/syntax_check.cpp 2>/dev/null && gcc -fsyntax-only -x c++ /tmp/syntax_check.cpp 2>/dev/null || echo "error"' | \
                       grep -c "error" || echo "0")

        if [ "$syntax_errors" -eq 0 ]; then
          echo "| Syntax Validation | ✅ PASS | All C++ files compile without syntax errors |" >> validation_report.md
        else
          echo "| Syntax Validation | ❌ FAIL | $syntax_errors files have syntax issues |" >> validation_report.md
        fi

        # TODO check
        todo_count=$(grep -r "TODO\|FIXME\|XXX" src/ include/ --include="*.cpp" --include="*.cu" --include="*.h" | grep -v "test_" | wc -l)
        if [ "$todo_count" -eq 0 ]; then
          echo "| Code Quality | ✅ PASS | No TODO/FIXME comments in production code |" >> validation_report.md
        else
          echo "| Code Quality | ⚠️ WARN | $todo_count TODO/FIXME comments found |" >> validation_report.md
        fi

        # Structure check
        if [ -d "src" ] && [ -d "include" ] && [ -d "tests" ] && [ -f "CMakeLists.txt" ]; then
          echo "| Project Structure | ✅ PASS | All required directories and files present |" >> validation_report.md
        else
          echo "| Project Structure | ❌ FAIL | Missing required directories or files |" >> validation_report.md
        fi

        echo "" >> validation_report.md
        echo "### 📋 Summary" >> validation_report.md
        echo "- **Validation Date**: $(date)" >> validation_report.md
        echo "- **Files Checked**: $(find src/ include/ tests/ -name "*.cpp" -o -name "*.cu" -o -name "*.cuh" -o -name "*.h" | wc -l)" >> validation_report.md
        echo "- **Test Files**: $(find tests/ -name "test_*.cpp" | wc -l)" >> validation_report.md
        echo "- **CUDA Runtime**: Not available (GitHub Actions limitation)" >> validation_report.md
        echo "" >> validation_report.md
        echo "### ⚠️ Important Notes" >> validation_report.md
        echo "- **GPU Testing**: Not available on GitHub Actions (no CUDA hardware)" >> validation_report.md
        echo "- **Compilation**: Code structure validated for syntax and organization" >> validation_report.md
        echo "- **Actual Testing**: Run tests locally on systems with CUDA-capable GPUs" >> validation_report.md
        echo "" >> validation_report.md
        echo "---" >> validation_report.md
        echo "*Generated by GitHub Actions CI*" >> validation_report.md

    - name: Comment PR with validation results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'validation_report.md';

          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
          } else {
            const fallbackComment = `## 🔍 GSDR Code Quality Check

✅ **Validation Status**: ${{ job.status == 'success' ? 'PASSED' : 'FAILED' }}

### What Was Checked:
- ✅ Syntax validation of all C++/CUDA files
- ✅ Code quality (TODO/FIXME comments)
- ✅ Project structure and required files
- ✅ Build system configuration

### Important Notes:
- **GPU Testing**: Not available on GitHub Actions
- **Compilation**: Code structure validated
- **Runtime Testing**: Requires CUDA-capable hardware

### For GPU Testing:
\`\`\`bash
mkdir build && cd build
cmake .. -DUSE_TESTS=ON
make
ctest --output-on-failure
\`\`\`

*Generated by GitHub Actions CI*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fallbackComment
            });
          }